### ISSUE TITLE
Binding an app to a Newrelic Service on OpenSource Cloud Foundry 

### ISSUE THREAD

**Issue by adamecjackson** [newrelic/newrelic-cf#1]
Does this newrelic-cf broker only work on Pivotal Cloud Foundry (PCF) instances or should it also work on CF Open Source editions?  Reason I ask is that I have successfully installed the service broker and bound some basic groovy apps to it on a PCF instance which lights up the new Relic APM dashboard.  However when installing on an open source edition of CF it fails when binding the same apps to the service.

Output of the error message is:
AJ-MBP:newrelic-cf adam$ cf bind-service aj-blue aj-monitor-cf
Binding service aj-monitor-cf to app aj-blue in org adam / space systems as adam.jackson@canopy-cloud.com...
FAILED
Server error, status code: 502, error code: 10001, message: The service broker rejected the request to http://service-broker-questioning-decresc.apps.demo.labs.cf.canopy-cloud.com/v2/service_instances/b6c56836-dbb9-48d2-8b5d-ad23d6ca90b0/service_bindings/bcf2f2ad-c6e9-4ff4-8a1c-c627e80f311c. Status Code: 400 Bad Request, Body: {"timestamp":1445613681936,"status":400,"error":"Bad Request","exception":"org.springframework.http.converter.HttpMessageNotReadableException","message":"Could not read JSON: Unrecognized field \"bind_resource\" (class com.nebhale.newrelicservicebroker.binding.BindingRequest), not marked as ignorable (6 known properties: \"serviceId\", \"plan_id\", \"planId\", \"service_id\", \"app_guid\", \"appGuid\"])\n at [Source: org.apache.catalina.connector.CoyoteInputStream@49865307; line: 1, column: 170](through reference chain: com.nebhale.newrelicservicebroker.binding.BindingRequest["bind_resource"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"bind_resource\" (class com.nebhale.newrelicservicebroker.binding.BindingRequest), not marked as ignorable (6 known properties: \"serviceId\", \"plan_id\", \"planId\", \"service_id\", \"app_guid\", \"appGuid\"])\n at [Source: org.apache.catalina.connector.CoyoteInputStream@49865307; line: 1, column: 170](through reference chain: com.nebhale.newrelicservicebroker.binding.BindingRequest["bind_resource"])","path":"/v2/service_instances/b6c56836-dbb9-48d2-8b5d-ad23d6ca90b0/service_bindings/bcf2f2ad-c6e9-4ff4-8a1c-c627e80f311c"}

Would appreciate some help on understanding the issue and confirmation on whether the broker should work on all CF environments or just Pivotal ones.

Adam

**Comment by adamecjackson** [comment]
FYI running CF open source edition 220

**Comment by tmartin14** [comment]
This should work with either open source or Pivotal CF.   I've not seen the exception that you've posted show up before so I'm at a bit of a loss.   Is version 220 the latest version?   It's been a while since I played with this.

**Comment by adamecjackson** [comment]
hi @tmartin14,

Thanks for the note.  Latest version is 222 (Released 19/10) but we are using 220.  

I'll continue to work with our engineers to see what if they can identify the issue and resolve.  If they do will post a response here.

Best

Adam

**Comment by tmartin14** [comment]
It appears there have been some changes in the Service Broker required parameters in CF lately that requires a new parameter.  We'll be looking into this as quickly as possible.   Sorry for the inconvenience.

**Comment by tmartin14** [comment]
Apologies for not updating this earlier, but as you probably noticed the fix for this issue was posted a couple of months ago.
